version: '3.1'

volumes:
  # data
  mongo-data:
    driver: local

services:

  nginx:
    container_name: api_bb
    build: ./services/api
    links:
      - php
    ports:
      - 8889:80
    working_dir: /application
    volumes:
      - ./application:/application
    extra_hosts:
      - "guarita:10.176.187.14"
      - "guarita.uniritter.local:10.176.187.14"

  php:
    container_name: php_bb
    build: ./services/php
    links:
      - mongo
    working_dir: /application
    volumes:
      - ./application:/application
    extra_hosts:
      - "guarita:10.176.187.14"
      - "guarita.uniritter.local:10.176.187.14"
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: api_bb_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: api_bb_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
